name: Weekly Build

on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 00:00 UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      release_type: weekly
